FROM python:3.13
WORKDIR /app
COPY pyproject.toml poetry.lock* /app/
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-root
COPY src /app/src
COPY alembic.ini /app/
COPY migrations /app/migrations
ENV PYTHONUNBUFFERED=1
